### PR TITLE
Carthage example

### PR DESCRIPTION
**Pull request by csacsi**

### CODE REVIEW

**Comment by jchen123** [comment]
weird @csacsi  how come this PR is huge?  shouldn't we have merged most things already?

**Comment by jchen123** [comment]
cc @SungjunApp

**Comment by csacsi** [comment]
Heyho,

Jun wanted an example for the SDK usage with Carthage, it is just the same example app as already provided, just with the Carthage setup

**Comment by SungjunApp** [comment]
@csacsi  Thank you, Csaba for building an app for using Carthage. I'll just keep this branch to verify our Carthage updates. 

So, this PR does not have to be merged. I'll just close this PR after checking a few things.

**Comment by jchen123** [comment]
@SungjunApp  so can we close this?

**Comment by SungjunApp** [comment]
Yes. I'll close this.

**Pull request closed without merging**
